import { writeFileSync } from 'fs';
import { promisify } from 'util';
import * as child from 'child_process';
import * as dedent from 'dedent';
const exec = promisify(child.exec);

async function createVersionsFile(filename: string) {
    const version = (await exec('git describe --tags HEAD')).stdout
        .toString()
        .trim();
    const content = dedent`
      // this file is automatically generated by git.version.ts script
      export const gitInfo = {
          version: '${version}',
      };`;

    writeFileSync(filename, content, { encoding: 'utf8' });
}

createVersionsFile('src/environments/version.ts');
