name: Build all tenants — development

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - tenant: ai4eosc
            webhook_url: https://webhooks.cloud.ai4eosc.eu/hooks/deploy-dashboard-ai4eosc-dev
          - tenant: imagine
            webhook_url: https://webhooks.cloud.ai4eosc.eu/hooks/deploy-dashboard-imagine-dev
    uses: ./.github/workflows/_build-reusable.yml
    with:
      tenant: ${{ matrix.tenant }}
      environment: dev
      webhook_url: ${{ matrix.webhook_url }}
    secrets:
      HARBOR_URL: ${{ secrets.HARBOR_URL }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      KEYCLOAK_SECRET: ${{ secrets.KEYCLOAK_SECRET }}
      HF_CLIENT_SECRET: ${{ secrets.HF_CLIENT_SECRET }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}