name: Build KMD4EOSC Dashboard

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-reusable.yml
    with:
      tenant: kmd4eosc
      environment: prod
      webhook_url: https://webhooks.cloud.ai4eosc.eu/hooks/deploy-dashboard-kmd4eosc-prod
    secrets:
      HARBOR_URL: ${{ secrets.HARBOR_URL }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      KEYCLOAK_SECRET: ${{ secrets.KEYCLOAK_SECRET }}
      HF_CLIENT_SECRET: ${{ secrets.HF_CLIENT_SECRET }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}