name: Build Imagine Dashboard

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to build'
        required: true
        default: 'prod'
        options:
          - prod
          - dev

jobs:
  build:
    uses: ./.github/workflows/_build-reusable.yml
    with:
      tenant: imagine
      environment: ${{ inputs.environment }}
      webhook_url: https://webhooks.cloud.ai4-dashboard/hooks/deploy-dashboard-imagine-${{ inputs.environment }}
    secrets:
      HARBOR_URL: ${{ secrets.HARBOR_URL }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      KEYCLOAK_SECRET: ${{ secrets.KEYCLOAK_SECRET }}
      HF_CLIENT_SECRET: ${{ secrets.HF_CLIENT_SECRET }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}