name: Build all tenants — development

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - tenant: ai4eosc
            webhook_url: https://webhooks.cloud.ai4-dashboard/hooks/deploy-dashboard-ai4eosc-dev
          - tenant: imagine
            webhook_url: https://webhooks.cloud.ai4-dashboard/hooks/deploy-dashboard-imagine-dev
    uses: ./.github/workflows/_build-reusable.yml
    with:
      tenant: ${{ matrix.tenant }}
      environment: dev
      webhook_url: ${{ matrix.webhook_url }}
    secrets: inherit