name: Build AI5EOSC Tutorials Dashboard

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-reusable.yml
    with:
      tenant: tutorials
      environment: prod
      webhook_url: https://webhooks.cloud.ai4-dashboard/hooks/deploy-dashboard-tutorials-prod
    secrets: inherit