name: Build Imagine Dashboard

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to build'
        required: true
        default: 'prod'
        options:
          - prod
          - dev

jobs:
  build:
    uses: ./.github/workflows/_build-reusable.yml
    with:
      tenant: imagine
      environment: ${{ inputs.environment }}
      webhook_url: https://webhooks.cloud.ai4-dashboard/hooks/deploy-dashboard-imagine-${{ inputs.environment }}
    secrets: inherit